### ISSUE TITLE
AttributeError: 'MultiLabelZeroShotGPTClassifier' object has no attribute 'key'

### ISSUE THREAD

**Issue by hasanhuz** [iryna-kondr/scikit-llm#100]
Hi

I got this error "AttributeError: 'MultiLabelZeroShotGPTClassifier' object has no attribute 'key'" while using below code:

from skllm import MultiLabelZeroShotGPTClassifier
from skllm.datasets import get_multilabel_classification_dataset

X, y = get_multilabel_classification_dataset()

clf = MultiLabelZeroShotGPTClassifier(max_labels=3)
clf.fit(X, y)
labels = clf.predict(X)

Thanks,

**Comment by OKUA1** [comment]
Hi @hasanhuz. 

I believe this problem is the same as https://github.com/iryna-kondr/scikit-llm/issues/93, hence I am going to close this issue to track it in one place. 

I assume you are using a jupyter notebook. As a short term fix, you can add anything after the last line (e.g. `print("done")`).
