### ISSUE TITLE
Add flag to control whether unknown labels are returned as None

### ISSUE THREAD

**Issue by Nadav-Barak** [iryna-kondr/scikit-llm#14]
`Additionally, Scikit-LLM will ensure that the obtained response contains a valid label. If this is not the case, a label will be selected randomly (label probabilities are proportional to label occurrences in the training set).`

In many pipelines it is better to return a None label to such examples instead of choosing one at random.
Would want a flag to control this behavior:
either set a specific label (like -1) in those cases / set None / select label at random (correct behavior)

**Comment by Nadav-Barak** [comment]
I can add functionality myself if you are fine with code contributions :)

**Comment by OKUA1** [comment]
Yes, I believe in some cases it might be beneficial to return None instead of a random label. 

This PR is somewhat related https://github.com/iryna-kondr/scikit-llm/pull/9

The only thing I am unsure about is what exact strategy to choose: 
Option 1: Add an additional (None) label to the prompt. The model is then able to choose this label. But in this case if the API call fails, a random label will be chosen anyway.
Option 2: Replace invalid labels with None during the output validation. 
Option 3: both previous options combined.

We are welcoming all contributions, so feel free to experiment with that. However, if possible I would ask to wait 2-3 days until we go through the initial PRs and establish the development workflow.

**Comment by Nadav-Barak** [comment]
Hey @OKUA1,
Sure, Iet me know when to start.
In addition if you have a kind of contribution guidelines that would be great.

**Comment by OKUA1** [comment]
Hi @Nadav-Barak, 

We have merged all pending PRs, so it should be fine to start implementing new features now. We do not have very strict contribution guidelines at the moment aside of what is written in `CONTRIBUTING.MD`. 

It would be great if you adjust the tests such that we have some test cases for the newly added functionality. 

Also, as someone expressed the wish to work on the docstrings for the existing methods, maybe you could get in touch with each other to coordinate the changes and avoid merge conflicts. 

We created a discord server for this purpose, so feel free to use it: https://discord.com/invite/NTaRnRpf

https://github.com/iryna-kondr/scikit-llm/issues/17
